# Generated by Django 4.2 on 2026-07-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
